import {
  User,
  Report,
  PotentialMatch,
  VerificationRecord,
  HandoverSchedule,
  NotificationItem,
  FinderContribution,
  Certificate,
  Reward,
  AuditLog,
  LeaderboardUser,
} from './types';

export const INSTITUTION_INFO = {
  fullName: 'PES College of Engineering, Mandya',
  shortName: 'PESCE Mandya',
  established: '1962',
  location: 'Mandya, Karnataka',
  tagline: 'Lost it? Pick it back.',
};

export const DEMO_USERS: Record<string, User> = {
  student_sarah: {
    id: 'usr_sarah',
    displayName: 'Sarah J.',
    role: 'student',
    college: 'PES College of Engineering, Mandya',
    shortCollege: 'PESCE Mandya',
    email: 'sarah.jenkins@pesce.ac.in',
    identifier: '4PS23CS084',
    department: 'Computer Science',
    semester: 'Year 3 (5th Sem)',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=250&auto=format&fit=crop&q=80',
    successfullyReturnedItems: 8,
    points: 80,
    rank: 7,
    verified: true,
  },
  student_rahul: {
    id: 'usr_rahul',
    displayName: 'Rahul K.',
    role: 'student',
    college: 'PES College of Engineering, Mandya',
    shortCollege: 'PESCE Mandya',
    email: 'rahul.k@pesce.ac.in',
    identifier: '4PS22ME049',
    department: 'Mechanical Dept',
    semester: 'Year 4',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=250&auto=format&fit=crop&q=80',
    successfullyReturnedItems: 15,
    points: 150,
    rank: 2,
    verified: true,
  },
  security_nair: {
    id: 'usr_nair',
    displayName: 'Officer R. Nair',
    role: 'security',
    college: 'PES College of Engineering, Mandya',
    shortCollege: 'PESCE Mandya',
    email: 'security.dispatch@pesce.ac.in',
    identifier: 'BADGE #CS-409',
    department: 'Campus Security & Custody',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=250&auto=format&fit=crop&q=80',
    successfullyReturnedItems: 142,
    points: 1420,
    rank: 0,
    verified: true,
  },
  admin_shivakumar: {
    id: 'usr_admin',
    displayName: 'Dr. N. Shivakumar',
    role: 'admin',
    college: 'PES College of Engineering, Mandya',
    shortCollege: 'PESCE Mandya',
    email: 'dean.welfare@pesce.ac.in',
    identifier: 'EMP-ADM-012',
    department: 'Dean of Student Welfare',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=250&auto=format&fit=crop&q=80',
    successfullyReturnedItems: 0,
    points: 0,
    rank: 0,
    verified: true,
  },
  faculty_divya: {
    id: 'usr_divya',
    displayName: 'Prof. Divya R.',
    role: 'faculty',
    college: 'PES College of Engineering, Mandya',
    shortCollege: 'PESCE Mandya',
    email: 'divya.r@pesce.ac.in',
    identifier: 'FAC-BS-104',
    department: 'Basic Sciences / Mathematics',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=250&auto=format&fit=crop&q=80',
    successfullyReturnedItems: 10,
    points: 100,
    rank: 5,
    verified: true,
  },
};

export const CAMPUS_BUILDINGS = [
  {
    id: 'bldg_cs',
    name: 'CS & Engineering Wing (Block B)',
    rooms: ['CS-204 (AI Lab)', 'CS-201 (Compiler Lab)', 'CS-302 (Seminar Hall)', 'Ground Floor Corridor'],
    lat: 12.5218,
    lng: 76.8951,
  },
  {
    id: 'bldg_main',
    name: 'Main Academic Block (Block A)',
    rooms: ['Dean Office (F1)', 'Admin Registrar Desk', 'Room 102 Lecture Hall', 'Physics Lab'],
    lat: 12.5224,
    lng: 76.8945,
  },
  {
    id: 'bldg_library',
    name: 'Central Library & Reading Hall',
    rooms: ['Reference Section (F1)', 'Digital Lab (F2)', 'Circulation Security Desk', 'Newspapers Reading Hall'],
    lat: 12.5229,
    lng: 76.8962,
  },
  {
    id: 'bldg_mech',
    name: 'Mechanical Workshop & Heavy Labs (Block D)',
    rooms: ['Machine Shop B-02', 'CAD Modeling Lab', 'Foundry Section', 'Robotics Bay'],
    lat: 12.5212,
    lng: 76.8967,
  },
  {
    id: 'bldg_gate1',
    name: 'Gate 1 Campus Security Exchange Kiosk',
    rooms: ['Main Safe Drop Hub', 'Smart Locker Bank #01-#16', 'Security Duty Desk'],
    lat: 12.5205,
    lng: 76.8955,
  },
  {
    id: 'bldg_cafe',
    name: 'Student Center & Cafeteria',
    rooms: ['Dining Court', 'Smart Locker #04', 'Student Council Desk'],
    lat: 12.5219,
    lng: 76.8938,
  },
];

export const INITIAL_REPORTS: Report[] = [
  {
    id: 'rep_001',
    ticketNumber: 'CP-2026-00142',
    type: 'LOST',
    complexity: 'DETAILED',
    reporterId: 'usr_sarah',
    reporterName: 'Sarah J.',
    reporterRole: 'student',
    reporterDepartment: 'Computer Science',
    reporterAvatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=250&auto=format&fit=crop&q=80',
    college: 'PES College of Engineering, Mandya',
    itemName: 'Lenovo ThinkPad X1 Carbon',
    category: 'electronics',
    brand: 'Lenovo',
    model: 'ThinkPad X1 Carbon Gen 9',
    color: 'Matte Black',
    description: 'Sleek black laptop misplaced in CS Lab during afternoon lecture. Red trackpoint button on keyboard.',
    identifyingFeatures: 'Linux Tux penguin vinyl decal near left USB-C port, red trackpoint',
    publicPhotoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCv9zHIjm9at5cJ5S6zxC6wxBzFw4IPNsm3eSKT1AH5HeyUnh-gZCBdOJQ22GXUyqdnW-o8wgKQe3hIZ2YtI7mpZAjkf5WsiF3hBaJh1u83mb0DFhXHApbCkzJA4DDyWZkgdXRk2leAQkwMTNr1Bm1QzT0AyNc7zMYLNO2HrQY9S_LTOFak3i8YZNtbg1yiJ78VFMjyqq--CC_TwzXY0epKGUV3d-URsukd0oRyamGj59WoambhMQkX',
    location: {
      building: 'CS & Engineering Wing (Block B)',
      floor: 'Floor 2',
      room: 'CS-204 (AI Lab)',
      areaDescription: 'Bench Row 3, Near Desk 14',
      precision: 'EXACT',
    },
    eventDate: 'Today',
    eventTime: '3:45 PM',
    status: 'POTENTIAL_MATCH',
    hasPrivateEvidence: true,
    privateEvidence: {
      serialNumber: 'PF-284920-X1',
      invoiceFileName: 'PESCE_Computer_Procurement_Receipt.pdf',
      privateNotes: 'Lockscreen wallpaper is dark matrix code with student ID 4PS23CS084 engraved on base corner.',
      uniqueMarks: 'Tiny scratch near HDMI port.',
    },
    createdAt: 'Today, 3:45 PM',
    updatedAt: 'Today, 3:55 PM',
  },
  {
    id: 'rep_002',
    ticketNumber: 'CP-2026-00148',
    type: 'FOUND',
    complexity: 'DETAILED',
    reporterId: 'usr_rahul',
    reporterName: 'Rahul K.',
    reporterRole: 'student',
    reporterDepartment: 'Mechanical Dept',
    reporterAvatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=250&auto=format&fit=crop&q=80',
    college: 'PES College of Engineering, Mandya',
    itemName: 'Black Lenovo ThinkPad',
    category: 'electronics',
    brand: 'Lenovo',
    model: 'ThinkPad Laptop',
    color: 'Dark Charcoal / Matte Black',
    description: 'Found closed black Lenovo laptop on desk in CS block hallway. Immediately turned into Smart Locker B-12 and notified security.',
    identifyingFeatures: 'Has dual stickers including penguin decal, intact condition',
    publicPhotoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA598EivMRXbOEBL1Y6ui_EmwZnYVYpVZx28ECEknp6OVeCP54Z5WepCBYxGTzSXCyii-ZbQuM8SOy_clXmxw0EpWFGVVgUrLHpNu8R9oGCsGtxKiwz2bU_GGUpW0lGAUNotn82qXrx2w36iTZ4-E8MofE9e7Gu49SSYx62mX6xLs_uItGDow3wxLx_L5fuRqEavCyyz3nlzwtst0My2GhNxqxDBGFU2O0IMuQ7149d_XYjYzIrogb_',
    location: {
      building: 'CS & Engineering Wing (Block B)',
      floor: 'Floor 2',
      room: 'CS-204 Lectern / Hallway',
      areaDescription: 'Deposited in Smart Locker B-12 at CS Tech Helpdesk',
      precision: 'EXACT',
    },
    eventDate: 'Today',
    eventTime: '3:52 PM',
    status: 'POTENTIAL_MATCH',
    hasPrivateEvidence: false,
    createdAt: 'Today, 3:52 PM',
    updatedAt: 'Today, 3:55 PM',
  },
  {
    id: 'rep_003',
    ticketNumber: 'CP-2026-00139',
    type: 'FOUND',
    complexity: 'SIMPLE',
    reporterId: 'usr_divya',
    reporterName: 'Prof. Divya R.',
    reporterRole: 'faculty',
    reporterDepartment: 'Basic Sciences',
    reporterAvatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=250&auto=format&fit=crop&q=80',
    college: 'PES College of Engineering, Mandya',
    itemName: 'Blue PESCE College ID Card',
    category: 'id_card',
    color: 'Blue Lanyard with College Crest',
    description: 'Found PESCE Student Smart Card dropped near Library Entrance.',
    identifyingFeatures: 'Computer Science student name starting with S.',
    publicPhotoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBdASmwN6d8XDUW42NWi7i15WmmiWqi6iDLpHxx45Ge_00zGjoHElKfepjrmjn3E3mGe-jS1UUoB9nrLRmuOcTR2R12RX77lFF39EcqeMKWuOCXNPtyrvfIy2ttuSWaL3IQIpDiqnjwbTAeJsNVG71ORy-2ZnvOxpKt-uQXrlx2K7kqH6qqDFAnCKwKhHKQeETafUoYOosgMjzJ7asa345FbGpWgWWbEZR8Va4dpeWrm3K4vDLStpu7',
    location: {
      building: 'Central Library & Reading Hall',
      floor: 'Ground Floor',
      room: 'Circulation Security Desk',
      areaDescription: 'Library Entrance Security Safe-Box',
      precision: 'EXACT',
    },
    eventDate: 'Yesterday',
    eventTime: '2:18 PM',
    status: 'FOUND',
    hasPrivateEvidence: false,
    createdAt: 'Yesterday, 2:18 PM',
    updatedAt: 'Yesterday, 2:18 PM',
  },
  {
    id: 'rep_004',
    ticketNumber: 'CP-2026-00135',
    type: 'FOUND',
    complexity: 'SIMPLE',
    reporterId: 'usr_rahul',
    reporterName: 'Rahul K.',
    reporterRole: 'student',
    reporterAvatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=250&auto=format&fit=crop&q=80',
    college: 'PES College of Engineering, Mandya',
    itemName: 'Dark Brown Bi-Fold Leather Wallet',
    category: 'wallet_bag',
    color: 'Dark Brown',
    description: 'Found genuine leather wallet on cafeteria table. Contains bus pass and hostel card.',
    identifyingFeatures: 'Silver metal zipper detail inside',
    publicPhotoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAT58f9vnstsAkwl2j_noqZteT7VAZsy-VkV-EX5YfZ1M7fceqao481zd30ZYb5nsZ_tRE-snXxtGfIg9Q1-sh_la9OFceO4te9uF8URGq0Hb8bQlyTBW9tv85DyikB62YP2Phk0LY7ig13CEO40OxL49A2sYg8m6h0lodXRzxTxynZztP8Hfwmh389AC8v8tCKQ7Eamk4Dflpjsa7a1A8JkNvCDP55C-4osXASYkgZMCrWBuyDGgha',
    location: {
      building: 'Student Center & Cafeteria',
      floor: 'Ground Floor',
      room: 'Dining Court',
      areaDescription: 'Deposited in Smart Locker #04',
      precision: 'EXACT',
    },
    eventDate: 'Today',
    eventTime: '1:25 PM',
    status: 'FOUND',
    hasPrivateEvidence: false,
    createdAt: 'Today, 1:25 PM',
    updatedAt: 'Today, 1:25 PM',
  },
  {
    id: 'rep_005',
    ticketNumber: 'CP-2026-00151',
    type: 'LOST',
    complexity: 'SIMPLE',
    reporterId: 'usr_rahul',
    reporterName: 'Rahul K.',
    reporterRole: 'student',
    reporterDepartment: 'Mechanical Dept',
    reporterAvatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=250&auto=format&fit=crop&q=80',
    college: 'PES College of Engineering, Mandya',
    itemName: 'Honda Shine Bike & Hostel Room 204 Key',
    category: 'keys',
    brand: 'Honda / Godrej',
    color: 'Silver with Red PESCE Rubber Keychain',
    description: 'Ring with two keys: bike ignition key and room lock key with a red rubber PESCE embossed keychain.',
    identifyingFeatures: 'Small silver whistle attached to the ring',
    location: {
      building: 'Mechanical Workshop & Heavy Labs (Block D)',
      floor: 'Ground Floor',
      room: 'Machine Shop B-02',
      areaDescription: 'Near Lathe Machine #4 bench',
      precision: 'EXACT',
    },
    eventDate: 'Today',
    eventTime: '11:15 AM',
    status: 'LOST',
    hasPrivateEvidence: false,
    createdAt: 'Today, 11:15 AM',
    updatedAt: 'Today, 11:15 AM',
  },
  {
    id: 'rep_006',
    ticketNumber: 'CP-2026-00153',
    type: 'FOUND',
    complexity: 'SIMPLE',
    reporterId: 'usr_nair',
    reporterName: 'Officer R. Nair',
    reporterRole: 'security',
    reporterAvatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=250&auto=format&fit=crop&q=80',
    college: 'PES College of Engineering, Mandya',
    itemName: 'Set of 3 Brass Keys with Lanyard',
    category: 'keys',
    color: 'Brass / Blue Lanyard',
    description: 'Found by security staff on pavement near Gate 1 parking shed. Deposited safely in Gate 1 custody rack.',
    identifyingFeatures: 'Blue lanyard with PESCE crest print',
    location: {
      building: 'Gate 1 Campus Security Exchange Kiosk',
      floor: 'Ground Floor',
      room: 'Main Safe Drop Hub',
      areaDescription: 'Gate 1 Safe Locker G-01',
      precision: 'EXACT',
    },
    eventDate: 'Today',
    eventTime: '12:40 PM',
    status: 'FOUND',
    hasPrivateEvidence: false,
    createdAt: 'Today, 12:40 PM',
    updatedAt: 'Today, 12:40 PM',
  },
  {
    id: 'rep_007',
    ticketNumber: 'CP-2026-00122',
    type: 'FOUND',
    complexity: 'DETAILED',
    reporterId: 'usr_divya',
    reporterName: 'Prof. Divya R.',
    reporterRole: 'faculty',
    reporterDepartment: 'Basic Sciences / Mathematics',
    reporterAvatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=250&auto=format&fit=crop&q=80',
    college: 'PES College of Engineering, Mandya',
    itemName: 'Casio fx-991CW ClassWiz Scientific Calculator',
    category: 'calculator',
    brand: 'Casio',
    model: 'fx-991CW',
    color: 'Black with White Keypad Accents',
    description: 'Found on podium after 2nd-hour Engineering Maths tutorial. Serial verified and safely returned to rightful owner.',
    identifyingFeatures: 'Small green circular dot sticker on back battery panel',
    location: {
      building: 'Main Academic Block (Block A)',
      floor: 'Floor 1',
      room: 'Room 102 Lecture Hall',
      areaDescription: 'Lectern Table',
      precision: 'EXACT',
    },
    eventDate: 'September 14, 2026',
    eventTime: '10:30 AM',
    status: 'RETURNED',
    hasPrivateEvidence: true,
    privateEvidence: {
      serialNumber: 'CASIO-991CW-8821B',
      privateNotes: 'Math lab student verified serial with syllabus record.',
    },
    createdAt: 'Sept 14, 2026',
    updatedAt: 'Sept 14, 2026',
  },
  {
    id: 'rep_008',
    ticketNumber: 'CP-2026-00129',
    type: 'LOST',
    complexity: 'SIMPLE',
    reporterId: 'usr_priya',
    reporterName: 'Priya S.',
    reporterRole: 'student',
    reporterDepartment: 'Electronics & Communication',
    reporterAvatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=250&auto=format&fit=crop&q=80',
    college: 'PES College of Engineering, Mandya',
    itemName: 'Casio fx-991EX ClassWiz Calculator',
    category: 'calculator',
    brand: 'Casio',
    model: 'fx-991EX',
    color: 'Carbon Fiber Finish Cover',
    description: 'Misplaced my scientific calculator during Digital Electronics lab test in EC wing.',
    identifyingFeatures: 'EC-3B written with permanent marker on inner slip lid',
    location: {
      building: 'CS & Engineering Wing (Block B)',
      floor: 'Floor 3',
      room: 'CS-302 (Seminar Hall)',
      areaDescription: 'Row 4 Desk',
      precision: 'APPROXIMATE',
    },
    eventDate: 'Yesterday',
    eventTime: '4:10 PM',
    status: 'LOST',
    hasPrivateEvidence: false,
    createdAt: 'Yesterday, 4:10 PM',
    updatedAt: 'Yesterday, 4:10 PM',
  },
  {
    id: 'rep_009',
    ticketNumber: 'CP-2026-00118',
    type: 'FOUND',
    complexity: 'SIMPLE',
    reporterId: 'usr_sarah',
    reporterName: 'Sarah J.',
    reporterRole: 'student',
    reporterDepartment: 'Computer Science',
    reporterAvatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=250&auto=format&fit=crop&q=80',
    college: 'PES College of Engineering, Mandya',
    itemName: 'Data Structures & Algorithms Handwritten Lab Binder',
    category: 'books_notes',
    color: 'Dark Green Spiral Notebook',
    description: 'Found comprehensive CS-3rd sem algorithms notes left in Digital Library terminal 12. Returned to owner.',
    identifyingFeatures: 'Cover page labeled "DSA Module 1 to 4 - 2026"',
    location: {
      building: 'Central Library & Reading Hall',
      floor: 'Floor 2',
      room: 'Digital Lab (F2)',
      areaDescription: 'Terminal #12',
      precision: 'EXACT',
    },
    eventDate: 'September 13, 2026',
    eventTime: '5:00 PM',
    status: 'RETURNED',
    hasPrivateEvidence: false,
    createdAt: 'Sept 13, 2026',
    updatedAt: 'Sept 13, 2026',
  },
  {
    id: 'rep_010',
    ticketNumber: 'CP-2026-00140',
    type: 'LOST',
    complexity: 'SIMPLE',
    reporterId: 'usr_manoj',
    reporterName: 'Manoj V.',
    reporterRole: 'student',
    reporterDepartment: 'Civil Engineering',
    reporterAvatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=250&auto=format&fit=crop&q=80',
    college: 'PES College of Engineering, Mandya',
    itemName: 'VTU Engineering Mechanics Textbook (Bhavikatti)',
    category: 'books_notes',
    brand: 'New Age International',
    color: 'Red and Yellow Paperback',
    description: 'Standard VTU syllabus textbook forgotten on stone benches outside civil department corridor.',
    identifyingFeatures: 'Civil dept syllabus checklist stapled on index page',
    location: {
      building: 'Main Academic Block (Block A)',
      floor: 'Ground Floor',
      room: 'Corridor Benches',
      areaDescription: 'Outside Dean Office',
      precision: 'APPROXIMATE',
    },
    eventDate: 'Today',
    eventTime: '9:30 AM',
    status: 'LOST',
    hasPrivateEvidence: false,
    createdAt: 'Today, 9:30 AM',
    updatedAt: 'Today, 9:30 AM',
  },
  {
    id: 'rep_011',
    ticketNumber: 'CP-2026-00160',
    type: 'FOUND',
    complexity: 'DETAILED',
    reporterId: 'usr_admin',
    reporterName: 'Dr. N. Shivakumar',
    reporterRole: 'admin',
    reporterDepartment: 'Dean of Student Welfare',
    reporterAvatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=250&auto=format&fit=crop&q=80',
    college: 'PES College of Engineering, Mandya',
    itemName: 'VTU Original Marks Card Folder (Mechanical Dept)',
    category: 'certificate',
    color: 'Navy Blue Leatherette Folder with Gold VTU Crest',
    description: 'Confidential academic dossier containing official 3rd & 4th semester grade cards. Secured in Dean Office Safe Locker.',
    identifyingFeatures: 'Mechanical Engineering student records from 2024-2025 batch',
    location: {
      building: 'Main Academic Block (Block A)',
      floor: 'Floor 1',
      room: 'Dean Office (F1)',
      areaDescription: 'Safe Deposit Vault',
      precision: 'EXACT',
    },
    eventDate: 'Today',
    eventTime: '10:00 AM',
    status: 'FOUND',
    hasPrivateEvidence: true,
    privateEvidence: {
      serialNumber: 'VTU-DOC-2026-4PS-ME',
      privateNotes: 'Contains verified VTU barcode seal and principal attestation.',
    },
    createdAt: 'Today, 10:00 AM',
    updatedAt: 'Today, 10:00 AM',
  },
  {
    id: 'rep_012',
    ticketNumber: 'CP-2026-00105',
    type: 'FOUND',
    complexity: 'SIMPLE',
    reporterId: 'usr_rahul',
    reporterName: 'Rahul K.',
    reporterRole: 'student',
    reporterDepartment: 'Mechanical Dept',
    reporterAvatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=250&auto=format&fit=crop&q=80',
    college: 'PES College of Engineering, Mandya',
    itemName: 'Wildcraft Black College Backpack',
    category: 'wallet_bag',
    brand: 'Wildcraft',
    color: 'Charcoal Black with Orange Trim',
    description: 'Found bag containing engineering drawing instruments and umbrella in workshop bay. Returned to owner Vikram B.',
    identifyingFeatures: 'Drawing mini-drafter case in side pocket',
    location: {
      building: 'Mechanical Workshop & Heavy Labs (Block D)',
      floor: 'Ground Floor',
      room: 'Workshop Bay',
      areaDescription: 'Deposited in Smart Locker W-01',
      precision: 'EXACT',
    },
    eventDate: 'September 12, 2026',
    eventTime: '3:20 PM',
    status: 'RETURNED',
    hasPrivateEvidence: false,
    createdAt: 'Sept 12, 2026',
    updatedAt: 'Sept 12, 2026',
  },
  {
    id: 'rep_013',
    ticketNumber: 'CP-2026-00164',
    type: 'LOST',
    complexity: 'DETAILED',
    reporterId: 'usr_karthik',
    reporterName: 'Karthik N.',
    reporterRole: 'student',
    reporterDepartment: 'Information Science',
    reporterAvatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=250&auto=format&fit=crop&q=80',
    college: 'PES College of Engineering, Mandya',
    itemName: 'OnePlus Buds Pro Wireless Earbuds',
    category: 'electronics',
    brand: 'OnePlus',
    model: 'Buds Pro',
    color: 'Matte Black Case with Metallic Stems',
    description: 'Misplaced charging capsule near gymkhana sports grounds after evening badminton practice.',
    identifyingFeatures: 'Small scratch on top charging lid, custom silicone ear tips',
    location: {
      building: 'Gymkhana & Sports Pavilion',
      floor: 'Ground Floor',
      room: 'Badminton Courts',
      areaDescription: 'Bleacher row 2',
      precision: 'APPROXIMATE',
    },
    eventDate: 'Yesterday',
    eventTime: '6:30 PM',
    status: 'LOST',
    hasPrivateEvidence: true,
    privateEvidence: {
      serialNumber: 'OP-BUDS-9421A',
      invoiceFileName: 'OnePlus_Store_Invoice.pdf',
    },
    createdAt: 'Yesterday, 6:30 PM',
    updatedAt: 'Yesterday, 6:30 PM',
  },
  {
    id: 'rep_014',
    ticketNumber: 'CP-2026-00167',
    type: 'FOUND',
    complexity: 'SIMPLE',
    reporterId: 'usr_divya',
    reporterName: 'Prof. Divya R.',
    reporterRole: 'faculty',
    reporterAvatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=250&auto=format&fit=crop&q=80',
    college: 'PES College of Engineering, Mandya',
    itemName: 'Ray-Ban Prescription Spectacles in Blue Case',
    category: 'other',
    brand: 'Ray-Ban',
    color: 'Matte Tortoise Shell / Blue Hard Case',
    description: 'Found spectacles case on student desk in Room 102. Deposited at Main Block staff desk.',
    identifyingFeatures: 'Anti-glare blue light coated lenses with titanium frame',
    location: {
      building: 'Main Academic Block (Block A)',
      floor: 'Floor 1',
      room: 'Room 102 Lecture Hall',
      areaDescription: 'Desk 18',
      precision: 'EXACT',
    },
    eventDate: 'Today',
    eventTime: '1:10 PM',
    status: 'FOUND',
    hasPrivateEvidence: false,
    createdAt: 'Today, 1:10 PM',
    updatedAt: 'Today, 1:10 PM',
  },
  {
    id: 'rep_015',
    ticketNumber: 'CP-2026-00098',
    type: 'FOUND',
    complexity: 'SIMPLE',
    reporterId: 'usr_ananya',
    reporterName: 'Ananya K.',
    reporterRole: 'student',
    reporterDepartment: 'Computer Science',
    reporterAvatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=250&auto=format&fit=crop&q=80',
    college: 'PES College of Engineering, Mandya',
    itemName: 'Karnataka KSRTC Student Bus Pass & Smart Card',
    category: 'id_card',
    color: 'Laminated Green Bus Pass with Mandya Division Stamp',
    description: 'Found near college entrance bus stop. Reunited with owner via verified campus protocol.',
    identifyingFeatures: 'Mandya to PESCE Route Pass #MND-8492',
    location: {
      building: 'Gate 1 Campus Security Exchange Kiosk',
      floor: 'Ground Floor',
      room: 'Security Duty Desk',
      areaDescription: 'Bus Stop Waiting Area',
      precision: 'EXACT',
    },
    eventDate: 'September 11, 2026',
    eventTime: '8:45 AM',
    status: 'RETURNED',
    hasPrivateEvidence: false,
    createdAt: 'Sept 11, 2026',
    updatedAt: 'Sept 11, 2026',
  },
];

export const INITIAL_MATCHES: PotentialMatch[] = [
  {
    id: 'match_001',
    lostReportId: 'rep_001',
    foundReportId: 'rep_002',
    lostReport: INITIAL_REPORTS[0],
    foundReport: INITIAL_REPORTS[1],
    confidenceScore: 87,
    confidenceLevel: 'High',
    matchingFactors: [
      { name: 'Item Classification', match: true, description: 'ThinkPad X1 Carbon vs Black Lenovo ThinkPad', strength: 'STRONG' },
      { name: 'Color Profile', match: true, description: 'Matte Black vs Dark Charcoal', strength: 'STRONG' },
      { name: 'Spatial Proximity', match: true, description: 'CS-204 Desk → 2F Hallway (15m offset within CS Wing)', strength: 'STRONG' },
      { name: 'Time Difference', match: true, description: '3:45 PM vs 3:52 PM (7 min delta)', strength: 'STRONG' },
      { name: 'Hardware Serial Number', match: false, description: 'Confidential • Protected in AES-256 Vault until Officer check', strength: 'STRONG' },
    ],
    status: 'PENDING',
    createdAt: 'Today, 3:55 PM',
  },
];

export const INITIAL_VERIFICATIONS: Record<string, VerificationRecord> = {
  match_001: {
    id: 'ver_001',
    matchId: 'match_001',
    claimantId: 'usr_sarah',
    claimantName: 'Sarah J.',
    status: 'UNDER_REVIEW',
    submittedEvidence: {
      serialNumberProvided: 'PF-284920-X1',
      lockscreenOrDecalHint: 'Red Tux Linux vinyl decal on palm rest, matrix wallpaper with USN 4PS23CS084',
      invoiceDocumentUrl: 'Verified PESCE Purchase Invoice Stamped #PF-284920-X1',
      additionalNotes: 'Turned in with Officer Nair supervising at Gate 1.',
    },
    reviewedBy: 'Officer R. Nair (Badge #CS-409)',
    reviewNotes: 'Evidence submitted: Serial #PF-284920-X1 and invoice receipt under review. Awaiting official verification approval from Gate 1 Security Desk.',
    reviewedAt: '',
    createdAt: 'Today, 4:02 PM',
    updatedAt: 'Today, 4:15 PM',
  },
  chat_priya: {
    id: 'ver_priya',
    matchId: 'chat_priya',
    claimantId: 'usr_sarah',
    claimantName: 'Sarah J.',
    status: 'UNDER_REVIEW',
    submittedEvidence: {
      serialNumberProvided: 'CASIO-FX991CW-8821',
      lockscreenOrDecalHint: 'Math lab batch sticker on reverse cover',
    },
    reviewedBy: 'Officer R. Nair (Badge #CS-409)',
    reviewNotes: 'Pending library log serial verification.',
    reviewedAt: '',
    createdAt: 'Today, 2:30 PM',
    updatedAt: 'Today, 2:30 PM',
  },
};

export const INITIAL_HANDOVERS: Record<string, HandoverSchedule> = {
  match_001: {
    id: 'hnd_001',
    matchId: 'match_001',
    lostReportId: 'rep_001',
    foundReportId: 'rep_002',
    location: 'Gate 1 Campus Security Exchange Kiosk',
    date: 'Today',
    time: '4:30 PM (Scheduled)',
    witnessOfficer: 'Officer R. Nair (Badge #CS-409)',
    status: 'SCHEDULED',
    ownerConfirmed: false,
    finderConfirmed: false,
    officerWitnessed: false,
  },
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_001',
    type: 'PRIORITY_ALERT',
    priority: true,
    title: 'Black Scientific Calculator in CS-204',
    message: 'Reported lost near Main Academic Block, Floor 2, Room CS-204 around 3:45 PM today.',
    targetingReason: "Why you're seeing this: Your verified PESCE enrollment associates you with Computer Science Block (CS-204) around 3:30–4:30 PM.",
    relatedReportId: 'rep_001',
    deepLinkTarget: 'report',
    timestamp: '12 min ago',
    read: false,
  },
  {
    id: 'notif_002',
    type: 'POTENTIAL_MATCH',
    priority: false,
    title: 'Potential Match Found (87% Similarity)',
    message: 'A deposited black laptop at Main Block Smart Locker B-12 correlates with your loss report. Review telemetry to verify.',
    relatedMatchId: 'match_001',
    deepLinkTarget: 'matches',
    timestamp: '18 min ago',
    read: false,
  },
  {
    id: 'notif_003',
    type: 'MORE_EVIDENCE_NEEDED',
    priority: false,
    title: 'Additional Evidence Needed',
    message: 'For claim on Lenovo ThinkPad X1 (Case #CP-89241). Security Officer R. Nair requested unique physical marker or receipt serial confirmation.',
    relatedMatchId: 'match_001',
    deepLinkTarget: 'verification',
    timestamp: '32 min ago',
    read: false,
  },
  {
    id: 'notif_004',
    type: 'HANDOVER_SCHEDULED',
    priority: false,
    title: 'Exchange at Gate 1 Security Kiosk',
    message: 'Exchange arranged with Rahul K. for today at 4:30 PM under supervision of Officer R. Nair.',
    relatedMatchId: 'match_001',
    deepLinkTarget: 'handover',
    timestamp: '1 hr ago',
    read: false,
  },
  {
    id: 'notif_005',
    type: 'GENERAL_LOST',
    priority: false,
    title: 'Blue Student Identity Card Reported Lost',
    message: 'Lost near Central Library Reading Hall entrance around 1:45 PM. Department of Mechanical Engineering lanyard.',
    relatedReportId: 'rep_003',
    deepLinkTarget: 'report',
    timestamp: '2 hrs ago',
    read: true,
  },
  {
    id: 'notif_006',
    type: 'HERO_RECOGNITION',
    priority: false,
    title: 'Return Milestone Achieved: +50 Points',
    message: 'Your verified return of the scientific calculator helped a fellow PESCE student. Your campus rank climbed from #14 to #11.',
    deepLinkTarget: 'heroes',
    timestamp: 'Yesterday',
    read: true,
  },
];

export const LEADERBOARD_USERS: LeaderboardUser[] = [
  { id: 'usr_ananya', rank: 1, name: 'Ananya K.', dept: 'CS Dept · Year 4', returns: 18, points: 180, avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=250&auto=format&fit=crop&q=80' },
  { id: 'usr_rahul', rank: 2, name: 'Rahul K.', dept: 'Mech Dept · Year 4', returns: 15, points: 150, avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=250&auto=format&fit=crop&q=80' },
  { id: 'usr_priya', rank: 3, name: 'Priya S.', dept: 'EC Dept · Year 3', returns: 13, points: 130, avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=250&auto=format&fit=crop&q=80' },
  { id: 'usr_karthik', rank: 4, name: 'Karthik N.', dept: 'ISE Department', returns: 11, points: 110, avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=250&auto=format&fit=crop&q=80' },
  { id: 'usr_divya', rank: 5, name: 'Prof. Divya R.', dept: 'Basic Sciences (Faculty)', returns: 10, points: 100, avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=250&auto=format&fit=crop&q=80' },
  { id: 'usr_manoj', rank: 6, name: 'Manoj V.', dept: 'Civil Engineering', returns: 9, points: 90, avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=250&auto=format&fit=crop&q=80' },
  { id: 'usr_sarah', rank: 7, name: 'Sarah J.', dept: 'CS Year 3', returns: 8, points: 80, avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=250&auto=format&fit=crop&q=80' },
  { id: 'usr_sneha', rank: 8, name: 'Sneha T.', dept: 'AI & DS Dept', returns: 7, points: 70, avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=250&auto=format&fit=crop&q=80' },
  { id: 'usr_vikram', rank: 9, name: 'Vikram B.', dept: 'Mechanical 6th Sem', returns: 6, points: 60, avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=250&auto=format&fit=crop&q=80' },
];

export const DEMO_CERTIFICATE: Certificate = {
  id: 'cert_001',
  certificateNumber: 'CP-HERO-2026-000084',
  userId: 'usr_sarah',
  userName: 'Sarah Jenkins',
  userDepartment: 'Department of Computer Science & Engineering',
  userUsn: 'PESCE/3RD-SEM/CIVIC-084',
  achievement: 'Certificate of Civic Integrity & Service',
  returnCountMilestone: 8,
  issueDate: 'September 10, 2026',
  authorizedBy: 'PES College of Engineering, Mandya',
  deanSignature: 'Dr. N. Shivakumar (Dean, Student Welfare)',
  securityChiefSignature: 'Capt. R. Deshmukh (Campus Security Chief)',
  hash: '8f92a0194bc7e89d14f11e892c4b01da',
};

export const DEMO_REWARDS: Reward[] = [
  {
    id: 'rew_001',
    name: "Dean's Letter of Commendation",
    description: 'Formal civic service recognition signed by Dean of Student Affairs for student placement dossiers.',
    requiredReturns: 5,
    requiredPoints: 50,
    status: 'READY_FOR_COLLECTION',
    approvalRequired: true,
  },
  {
    id: 'rew_002',
    name: 'PESCE Commemorative Hoodie & Voucher',
    description: 'Exclusive campus green hoodie plus a ₹500 engineering bookstore token.',
    requiredReturns: 10,
    requiredPoints: 100,
    status: 'LOCKED',
    approvalRequired: true,
  },
  {
    id: 'rew_003',
    name: 'President Civic Leadership Trophy',
    description: 'Institutional honor bestowed at Annual College Day with verified ledger citation.',
    requiredReturns: 25,
    requiredPoints: 250,
    status: 'LOCKED',
    approvalRequired: true,
  },
];
